load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//darparu:__subpackages__"])

cc_library(
    name = "simple_3d",
    hdrs = ["simple_3d.h"],
    deps = [
        "//darparu/renderer:io_control",
    ],
)
