load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//darparu:__subpackages__"])

cc_library(
    name = "orbit",
    hdrs = ["orbit.h"],
    deps = [
        "//darparu/renderer:camera",
    ],
)
